config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books
  resources :libraries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :authorships
    has_many :books, through: :authorships
end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :authorships
    has_many :authors, through: :authorships
    has_many :book_libraries
    has_many :libraries, through: :book_libraries
end

app/models/book_library.rb
class BookLibrary < ApplicationRecord
  belongs_to :book
  belongs_to :library
end

app/models/library.rb
class Library < ApplicationRecord
    has_many :book_libraries
    has_many :books, through: :book_libraries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def edit
  end

  def create
    @current_author = Author.new(author_params)
    if @current_author.save
      redirect_to @current_author, notice: 'Author was successfully created.'
    else
      render :new
    end
  end

  def update
    if @current_author.update(author_params)
      redirect_to @current_author, notice: 'Author was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @current_author.destroy
    redirect_to authors_url, notice: 'Author was successfully destroyed.'
  end

  private

  def set_author
    @current_author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :email_address, :contact_number)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.new(book_params)
    if book.save
      redirect_to book
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to book
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :publication_date, :edition, author_ids: [], library_ids: [])
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    @libraries = Library.all
  end

  def show
    @library = Library.find(params[:id])
  end

  def new
    @library = Library.new
  end

  def create
    library = Library.new(library_params)
    if library.save
      redirect_to library
    else
      render :new
    end
  end

  def edit
    @library = Library.find(params[:id])
  end

  def update
    library = Library.find(params[:id])
    if library.update(library_params)
      redirect_to library
    else
      render :edit
    end
  end

  def destroy
    library = Library.find(params[:id])
    library.destroy
    redirect_to libraries_path
  end

  private

  def library_params
    params.require(:library).permit(:name, :location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/authors/_author.html.erb
<p>
  Name: <%= author.name %><br>
  Email: <%= author.email_address %><br>
  Contact: <%= author.contact_number %>
</p>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
    <% if author.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>
        <ul>
          <% author.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :email_address %>
      <%= form.text_field :email_address %>
    </div>
  
    <div class="field">
      <%= form.label :contact_number %>
      <%= form.text_field :contact_number %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>
<%= render 'form', author: @author %>
<%= link_to 'Back', author_path(@current_author) %>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to "Show this author", author %>
    </p>
  <% end %>
</div>

<%= link_to "New Author", new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render 'form', author: @author %>
<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<h1><%= @current_author.name %></h1>
<p>Email: <%= @current_author.email_address %></p>
<p>Contact Number: <%= @current_author.contact_number %></p>
<h2>Books</h2>
<ul>
  <% @current_author.books.each do |book| %>
    <li><%= link_to book.name, book_path(book) %></li>
  <% end %>
</ul>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
    <% if book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :publication_date %>
      <%= form.datetime_select :publication_date %>
    </div>
  
    <div class="field">
      <%= form.label :edition %>
      <%= form.number_field :edition %>
    </div>
  
    <div class="field">
      <%= form.label :authors %>
      <%= form.collection_select :author_ids, Author.all, :id, :name, {}, { multiple: true } %>
    </div>
  
    <div class="field">
      <%= form.label :libraries %>
      <%= form.collection_select :library_ids, Library.all, :id, :name, {}, { multiple: true } %>
  
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render 'form', book: @book %>
<%= link_to 'Back', book_path(@book) %>

app/views/books/index.html.erb
<h1>Books</h1>
<%= link_to 'New Book', new_book_path %>
<ul>
  <% @books.each do |book| %>
    <li>
      <%= link_to book.name, book_path(book) %> |
      <%= link_to 'Edit', edit_book_path(book) %> |
      <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form', book: @book %>
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>
<p>Publication Date: <%= @book.publication_date %></p>
<p>Edition: <%= @book.edition %></p>
<h2>Authors</h2>
<ul>
  <% @book.authors.each do |author| %>
    <li><%= link_to author.name, author_path(author) %></li>
  <% end %>
</ul>
<h2>Libraries</h2>
<ul>
  <% @book.libraries.each do |library| %>
    <li><%= link_to library.name, library_path(library) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/libraries/_form.html.erb
<%= form_with(model: library, local: true) do |form| %>
    <% if library.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>
        <ul>
          <% library.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/libraries/edit.html.erb
<h1>Edit Library</h1>
<%= render 'form', library: @library %>
<%= link_to 'Back', library_path(@library) %>

app/views/libraries/index.html.erb
<h1>Libraries</h1>
<%= link_to 'New Library', new_library_path %>
<ul>
  <% @libraries.each do |library| %>
    <li>
      <%= link_to library.name, library_path(library) %> |
      <%= link_to 'Edit', edit_library_path(library) %> |
      <%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/libraries/new.html.erb
<h1>New Library</h1>
<%= render 'form', library: @library %>
<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<h1><%= @library.name %></h1>
<p>Location: <%= @library.location %></p>
<h2>Books</h2>
<ul>
  <% @library.books.each do |book| %>
    <li>
      <%= link_to book.name, book_path(book) %> -
      Authors: <%= book.authors.map { |author| link_to author.name, author_path(author) }.join(", ").html_safe %>
    </li>
  <% end %>
</ul>